spring:
  datasource:
    url: jdbc:mysql://localhost:3306/docker?characterEncoding=utf-8
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: create
  hadoop.:
    fs-uri: hdfs://172.17.4.27:9000

server:
  port: 8089

docker.server.url: tcp://132.232.188.238:2376

